kind = "DojoContract"
class_hash = "0xc9382910fa890b894c41559a36940731f8ed46a72be1a46833d6114dec0f39"
original_class_hash = "0xc9382910fa890b894c41559a36940731f8ed46a72be1a46833d6114dec0f39"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/txspaces_systems_game_actions_GameActions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "txspaces::systems::game_actions::GameActions"
