kind = "DojoContract"
class_hash = "0x2d53335533b0ce6daa6fc95238a1549aefcac9136a34ef4f55a5257dca494c8"
original_class_hash = "0x2d53335533b0ce6daa6fc95238a1549aefcac9136a34ef4f55a5257dca494c8"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/txspaces_systems_game_actions_GameActions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "txspaces::systems::game_actions::GameActions"
