kind = "DojoModel"
class_hash = "0x406ff65cb8340f01826b3f1628b60c294d1b32f8182e7f1c3d04a80e4c61522"
original_class_hash = "0x406ff65cb8340f01826b3f1628b60c294d1b32f8182e7f1c3d04a80e4c61522"
abi = "manifests/testnet/abis/base/models/lethal_models_character_character.json"
name = "lethal::models::character::character"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "pos_idx"
type = "u8"
key = true

[[members]]
name = "level"
type = "u16"
key = false
