kind = "DojoModel"
class_hash = "0x1b98562c7da3ac459136baa26f41a65b40af07b0f7b28b701d9dadd1d85e844"
original_class_hash = "0x1b98562c7da3ac459136baa26f41a65b40af07b0f7b28b701d9dadd1d85e844"
abi = "manifests/testnet/abis/base/models/lethal_models_user_data_user_data.json"
name = "lethal::models::user_data::user_data"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false

[[members]]
name = "balance"
type = "u128"
key = false

[[members]]
name = "snapshoted_at"
type = "u64"
key = false
