kind = "DojoModel"
class_hash = "0x138531a5aec076abfb9c59b4d0f83353a2d6522579d177344a39814629730ea"
original_class_hash = "0x138531a5aec076abfb9c59b4d0f83353a2d6522579d177344a39814629730ea"
abi = "manifests/testnet/abis/base/models/lethal_models_character_level_character_level.json"
name = "lethal::models::character_level::character_level"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "u32"
key = true

[[members]]
name = "count"
type = "u32"
key = false
