kind = "DojoModel"
class_hash = "0x790f408d1913acb651dd5e0d9b6cbba6a29ea63715edd3e587a7947bccbebea"
original_class_hash = "0x790f408d1913acb651dd5e0d9b6cbba6a29ea63715edd3e587a7947bccbebea"
abi = "manifests/testnet/abis/base/models/lethal_events_character_bought.json"
name = "lethal::events::character_bought"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "created_at"
type = "u64"
key = true

[[members]]
name = "index"
type = "u8"
key = false

[[members]]
name = "level"
type = "u16"
key = false
