// Generated by dojo-bindgen on Tue, 23 Jul 2024 09:23:13 +0000. Do not modify this file manually.
import { Account } from "starknet";
import {
    Clause,
    Client,
    ModelClause,
    createClient,
    valueToToriiValueAndOperator,
} from "@dojoengine/torii-client";
import {
    LOCAL_KATANA,
    LOCAL_RELAY,
    LOCAL_TORII,
    createManifestFromJson,
} from "@dojoengine/core";

// Type definition for `core::byte_array::ByteArray` struct
export interface ByteArray {
    data: string[];
    pending_word: string;
    pending_word_len: number;
}

// Type definition for `txspaces::models::invitation_code::InvitationCode` struct
export interface InvitationCode {
    code: string;
    player: string;
    limit: number;
    usedCount: number;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
type Option<A> = { type: 'Some'; data: A; } | { type: 'None'; }

// Type definition for `txspaces::models::character::Character` struct
export interface Character {
    player: string;
    pos_idx: number;
    level: number;
}


// Type definition for `txspaces::models::random::Random` struct
export interface Random {
    id: number;
    s0: bigint;
    s1: bigint;
}


// Type definition for `txspaces::models::user_data::UserData` struct
export interface UserData {
    player: string;
    code: string;
    initialized: boolean;
    balance: bigint;
    snapshoted_at: bigint;
}


// Type definition for `txspaces::models::burner::Burner` struct
export interface Burner {
    burner: string;
    player: string;
}


// Type definition for `txspaces::models::character_level::CharacterLevel` struct
export interface CharacterLevel {
    player: string;
    level: number;
    count: number;
}


class BaseCalls {
    contractAddress: string;
    account?: Account;

    constructor(contractAddress: string, account?: Account) {
        this.account = account;
        this.contractAddress = contractAddress;
    }

    async execute(entrypoint: string, calldata: any[] = []): Promise<void> {
        if (!this.account) {
            throw new Error("No account set to interact with dojo_starter");
        }

        await this.account.execute(
            {
                contractAddress: this.contractAddress,
                entrypoint,
                calldata,
            },
            undefined,
            {
                maxFee: 0,
            }
        );
    }
}

class AdminCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }

    async seed(seed: bigint): Promise<void> {
        try {
            await this.execute("seed", [seed])
        } catch (error) {
            console.error("Error executing seed:", error);
            throw error;
        }
    }

    async addDefaultCode(id: string): Promise<void> {
        try {
            await this.execute("add_default_code", [id])
        } catch (error) {
            console.error("Error executing addDefaultCode:", error);
            throw error;
        }
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }
}
class GameActionsCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async buy(action_id: string, level: number): Promise<void> {
        try {
            await this.execute("buy", [action_id,
                level])
        } catch (error) {
            console.error("Error executing buy:", error);
            throw error;
        }
    }

    async delete(action_id: string, idx: number): Promise<void> {
        try {
            await this.execute("delete", [action_id,
                idx])
        } catch (error) {
            console.error("Error executing delete:", error);
            throw error;
        }
    }

    async merge(action_id: string, idx1: number, idx2: number): Promise<void> {
        try {
            await this.execute("merge", [action_id,
                idx1,
                idx2])
        } catch (error) {
            console.error("Error executing merge:", error);
            throw error;
        }
    }

    async getBoard(player: string): Promise<void> {
        try {
            await this.execute("get_board", [player])
        } catch (error) {
            console.error("Error executing getBoard:", error);
            throw error;
        }
    }

    async getCharacterIdleRate(levels: number[]): Promise<void> {
        try {
            await this.execute("get_character_idle_rate", [levels])
        } catch (error) {
            console.error("Error executing getCharacterIdleRate:", error);
            throw error;
        }
    }

    async getCharacterPrices(buy_counts: bigint[], levels: bigint[]): Promise<void> {
        try {
            await this.execute("get_character_prices", [buy_counts,
                levels])
        } catch (error) {
            console.error("Error executing getCharacterPrices:", error);
            throw error;
        }
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }
}
class UserCalls extends BaseCalls {
    constructor(contractAddress: string, account?: Account) {
        super(contractAddress, account);
    }

    async dojoResource(): Promise<void> {
        try {
            await this.execute("dojo_resource", [])
        } catch (error) {
            console.error("Error executing dojoResource:", error);
            throw error;
        }
    }

    async init(code: string): Promise<void> {
        try {
            await this.execute("init", [code])
        } catch (error) {
            console.error("Error executing init:", error);
            throw error;
        }
    }

    async whitelistedInit(): Promise<void> {
        try {
            await this.execute("whitelisted_init", [])
        } catch (error) {
            console.error("Error executing whitelistedInit:", error);
            throw error;
        }
    }

    async registerBurner(burnerAddress: string): Promise<void> {
        try {
            await this.execute("register_burner", [burnerAddress])
        } catch (error) {
            console.error("Error executing registerBurner:", error);
            throw error;
        }
    }

    async userBalance(player: string): Promise<void> {
        try {
            await this.execute("user_balance", [player])
        } catch (error) {
            console.error("Error executing userBalance:", error);
            throw error;
        }
    }

    async dojoInit(): Promise<void> {
        try {
            await this.execute("dojo_init", [])
        } catch (error) {
            console.error("Error executing dojoInit:", error);
            throw error;
        }
    }
}

type Query = Partial<{
    InvitationCode: ModelClause<InvitationCode>;
    Character: ModelClause<Character>;
    Random: ModelClause<Random>;
    UserData: ModelClause<UserData>;
    Burner: ModelClause<Burner>;
    CharacterLevel: ModelClause<CharacterLevel>;
}>;

type ResultMapping = {
    InvitationCode: InvitationCode;
    Character: Character;
    Random: Random;
    UserData: UserData;
    Burner: Burner;
    CharacterLevel: CharacterLevel;
};

type QueryResult<T extends Query> = {
    [K in keyof T]: K extends keyof ResultMapping ? ResultMapping[K] : never;
};

// Only supports a single model for now, since torii doesn't support multiple models
// And inside that single model, there's only support for a single query.
function convertQueryToToriiClause(query: Query): Clause | undefined {
    const [model, clause] = Object.entries(query)[0];

    if (Object.keys(clause).length === 0) {
        return undefined;
    }

    const clauses: Clause[] = Object.entries(clause).map(([key, value]) => {
        return {
            Member: {
                model,
                member: key,
                ...valueToToriiValueAndOperator(value),
            },
        } satisfies Clause;
    });

    return clauses[0];
}
type GeneralParams = {
    toriiUrl?: string;
    relayUrl?: string;
    account?: Account;
};

type InitialParams = GeneralParams &
    (
        | {
                rpcUrl?: string;
                worldAddress: string;
                adminAddress: string;
    gameActionsAddress: string;
    userAddress: string;
            }
        | {
                manifest: any;
            }
    );

export class Txspaces {
    rpcUrl: string;
    toriiUrl: string;
    toriiPromise: Promise<Client>;
    relayUrl: string;
    worldAddress: string;
    private _account?: Account;
    admin: AdminCalls;
    adminAddress: string;
    gameActions: GameActionsCalls;
    gameActionsAddress: string;
    user: UserCalls;
    userAddress: string;

    constructor(params: InitialParams) {
        if ("manifest" in params) {
            const config = createManifestFromJson(params.manifest);
            this.rpcUrl = config.world.metadata.rpc_url;
            this.worldAddress = config.world.address;

            const adminAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::admin::admin"
            )?.address;

            if (!adminAddress) {
                throw new Error("No admin contract found in the manifest");
            }

            this.adminAddress = adminAddress;
    const gameActionsAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::gameActions::gameActions"
            )?.address;

            if (!gameActionsAddress) {
                throw new Error("No gameActions contract found in the manifest");
            }

            this.gameActionsAddress = gameActionsAddress;
    const userAddress = config.contracts.find(
                (contract) =>
                    contract.name === "dojo_starter::systems::user::user"
            )?.address;

            if (!userAddress) {
                throw new Error("No user contract found in the manifest");
            }

            this.userAddress = userAddress;
        } else {
            this.rpcUrl = params.rpcUrl || LOCAL_KATANA;
            this.worldAddress = params.worldAddress;
            this.adminAddress = params.adminAddress;
    this.gameActionsAddress = params.gameActionsAddress;
    this.userAddress = params.userAddress;
        }
        this.toriiUrl = params.toriiUrl || LOCAL_TORII;
        this.relayUrl = params.relayUrl || LOCAL_RELAY;
        this._account = params.account;
        this.admin = new AdminCalls(this.adminAddress, this._account);
    this.gameActions = new GameActionsCalls(this.gameActionsAddress, this._account);
    this.user = new UserCalls(this.userAddress, this._account);

        this.toriiPromise = createClient([], {
            rpcUrl: this.rpcUrl,
            toriiUrl: this.toriiUrl,
            worldAddress: this.worldAddress,
            relayUrl: this.relayUrl,
        });
    }

    get account(): Account | undefined {
        return this._account;
    }

    set account(account: Account) {
        this._account = account;
        this.admin = new AdminCalls(this.adminAddress, this._account);
    this.gameActions = new GameActionsCalls(this.gameActionsAddress, this._account);
    this.user = new UserCalls(this.userAddress, this._account);
    }

    async query<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        return {
            torii,
            findEntities: async () => this.findEntities(query, limit, offset),
        };
    }

    async findEntities<T extends Query>(query: T, limit = 10, offset = 0) {
        const torii = await this.toriiPromise;

        const clause = convertQueryToToriiClause(query);

        const toriiResult = await torii.getEntities({
            limit,
            offset,
            clause,
        });

        return toriiResult as Record<string, QueryResult<T>>;
    }

    async findEntity<T extends Query>(query: T) {
        const result = await this.findEntities(query, 1);

        if (Object.values(result).length === 0) {
            return undefined;
        }

        return Object.values(result)[0] as QueryResult<T>;
    }
}