[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x69cbccb9ebcf1db98b70c8c613efab4b92a26d84301b9bf2aaa63900aefdf1f"
transaction_hash = "0x6f66dda6638e92958a133994fa31509d2d4e9afa714b306b95390f09d6322c0"
block_number = 3
seed = "lethal"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x4f5c06f4a67137ea12bba5f9079b9a9b9b99f41db30312661bcbbb4cd687c85"
class_hash = "0x12b76aa176ac061d9b73eae52470c7a71fc8b3f54712513ad7f44d9b039d5f4"
original_class_hash = "0x12b76aa176ac061d9b73eae52470c7a71fc8b3f54712513ad7f44d9b039d5f4"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/lethal_systems_game_actions_GameActions.json"
reads = []
writes = []
computed = []
name = "lethal::systems::game_actions::GameActions"

[[contracts]]
kind = "DojoContract"
address = "0x4f783593710a61545745d6600b6ee975ffc5e78169df85a4e584a3eb0e3f613"
class_hash = "0x468a5d65f0545b9ed2823b80928c59890678722d0ad0a1e0a3a5f5cdb6fd162"
original_class_hash = "0x468a5d65f0545b9ed2823b80928c59890678722d0ad0a1e0a3a5f5cdb6fd162"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/lethal_systems_user_User.json"
reads = []
writes = []
computed = []
name = "lethal::systems::user::User"

[[models]]
kind = "DojoModel"
class_hash = "0x406ff65cb8340f01826b3f1628b60c294d1b32f8182e7f1c3d04a80e4c61522"
original_class_hash = "0x406ff65cb8340f01826b3f1628b60c294d1b32f8182e7f1c3d04a80e4c61522"
abi = "abis/deployments/models/lethal_models_character_character.json"
name = "lethal::models::character::character"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "pos_idx"
type = "u8"
key = true

[[models.members]]
name = "level"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x138531a5aec076abfb9c59b4d0f83353a2d6522579d177344a39814629730ea"
original_class_hash = "0x138531a5aec076abfb9c59b4d0f83353a2d6522579d177344a39814629730ea"
abi = "abis/deployments/models/lethal_models_character_level_character_level.json"
name = "lethal::models::character_level::character_level"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "level"
type = "u32"
key = true

[[models.members]]
name = "count"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2920b8df3d8bf589036c5e4675fb9ca2a04dbbf52f4f43dec27ac0878e9882"
original_class_hash = "0x2920b8df3d8bf589036c5e4675fb9ca2a04dbbf52f4f43dec27ac0878e9882"
abi = "abis/deployments/models/lethal_models_user_data_user_data.json"
name = "lethal::models::user_data::user_data"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "initilized"
type = "bool"
key = false

[[models.members]]
name = "balance"
type = "u128"
key = false

[[models.members]]
name = "snapshoted_at"
type = "u64"
key = false
