kind = "DojoContract"
class_hash = "0x31f163ad70dce8cae7c8cf42f73034ffce11405d431262aff3188b101396c6a"
original_class_hash = "0x31f163ad70dce8cae7c8cf42f73034ffce11405d431262aff3188b101396c6a"
base_class_hash = "0x0"
abi = "manifests/testnet/abis/base/contracts/txspaces_systems_admin_Admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "txspaces::systems::admin::Admin"
