kind = "DojoContract"
class_hash = "0x35fbbcaad13b3caa7dcc1e772bbe3c12183180a5dd59af9ab040bff084013ed"
original_class_hash = "0x35fbbcaad13b3caa7dcc1e772bbe3c12183180a5dd59af9ab040bff084013ed"
base_class_hash = "0x0"
abi = "manifests/testnet/abis/base/contracts/txspaces_systems_game_actions_GameActions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "txspaces::systems::game_actions::GameActions"
