kind = "DojoModel"
class_hash = "0x7665d84154933b9708a32003839a548570e0ff7c53d2c1199ec31a292ed18e3"
original_class_hash = "0x7665d84154933b9708a32003839a548570e0ff7c53d2c1199ec31a292ed18e3"
abi = "manifests/dev/abis/base/models/lethal_events_character_merged.json"
name = "lethal::events::character_merged"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "created_at"
type = "u64"
key = true

[[members]]
name = "index1"
type = "u8"
key = false

[[members]]
name = "index2"
type = "u8"
key = false

[[members]]
name = "prev_level"
type = "u16"
key = false

[[members]]
name = "next_level"
type = "u16"
key = false
