kind = "DojoModel"
class_hash = "0x81a1169daf23f2242217414a6e9713dbdd5569605f9e1e76a472e3225771a0"
original_class_hash = "0x81a1169daf23f2242217414a6e9713dbdd5569605f9e1e76a472e3225771a0"
abi = "manifests/dev/abis/base/models/txspaces_models_burner_burner.json"
name = "txspaces::models::burner::burner"

[[members]]
name = "burner"
type = "ContractAddress"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = false
